import AppKit
import Observation

struct ClipboardEntry: Identifiable {
    let id = UUID()
    let text: String
}

@Observable
final class ClipboardStore {
    static let shared = ClipboardStore()
    var enabled = UserDefaults.standard.bool(forKey: "clipboardHistory") {
        didSet {
            UserDefaults.standard.set(enabled, forKey: "clipboardHistory")
            lastChange = NSPasteboard.general.changeCount
        }
    }
    private(set) var items: [ClipboardEntry] = []
    private var lastChange = NSPasteboard.general.changeCount
    private var timer: Timer?
    private init() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.75, repeats: true) { [weak self] _ in self?.read() }
    }
    private func read() {
        let pasteboard = NSPasteboard.general
        guard enabled, pasteboard.changeCount != lastChange else { return }
        lastChange = pasteboard.changeCount
        let excluded = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]
        guard !excluded.contains(where: { pasteboard.types?.contains(NSPasteboard.PasteboardType($0)) == true }),
              let text = pasteboard.string(forType: .string), !text.isEmpty, text.utf8.count <= 100_000 else { return }
        items.removeAll { $0.text == text }
        items.insert(ClipboardEntry(text: text), at: 0)
        if items.count > 50 { items.removeLast() }
    }
    func copy(_ item: ClipboardEntry) {
        NSPasteboard.general.clearContents()
        NSPasteboard.general.setString(item.text, forType: .string)
        lastChange = NSPasteboard.general.changeCount
    }
    func clear() { items.removeAll() }
}
